# path: .github/workflows/transform-sap.yml
name: Transform SAP Excel
on:
  push:
    paths:
      - "sklady_porovnani/input/**/*.xlsx"
      - "sklady_porovnani/scripts/**"
      - "sklady_porovnani/requirements.txt"
      - ".github/workflows/transform-sap.yml"
jobs:
  run-transform:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r sklady_porovnani/requirements.txt
      - name: Run transform on all input XLSX
        shell: bash
        run: |
          shopt -s nullglob
          mkdir -p sklady_porovnani/output
          for f in sklady_porovnani/input/*.xlsx; do
            echo "Processing: $f"
            python sklady_porovnani/scripts/transform_sap.py \
              --input "$f" \
              --output "sklady_porovnani/output/$(basename "${f%.*}")_SAP.xlsx"
          done
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: SAP-outputs
          path: sklady_porovnani/output/*.xlsx
          if-no-files-found: warn 